mywebsite1/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls.static import static
from goods import user_view, goods_view, address_view, orders_view
from mywebsite1 import settings

"""
2.0 版本
"""
urlpatterns = [
    path('', user_view.index),
    path('admin/', admin.site.urls),
    path('index/', user_view.index, name='index'),
    path('login_action/', user_view.login_action, name='login_action'),
    path('logout/', user_view.logout, name='logout'),
    path('register/', user_view.register, name='register'),
    path('user_info/', user_view.user_info, name='user_info'),
    path('change_password/', user_view.change_password),
    path('goods_view/', goods_view.goods_view),
    path('search_name/', goods_view.search_name),
    re_path(r'^view_goods/(?P<good_id>[0-9]+)/$', goods_view.good_detail),
    re_path(r'^add_chart/(?P<good_id>[0-9]+)/(?P<sign>[0-9]+)/$', goods_view.add_chart),
    path('view_chart/', goods_view.view_chart),
    re_path(r'^update_chart/(?P<good_id>[0-9]+)/$', goods_view.update_chart),
    re_path(r'^remove_chart/(?P<good_id>[0-9]+)/$', goods_view.remove_chart),
    path('remove_chart_all/', goods_view.remove_chart_all),
    path('view_address/', address_view.view_address),
    re_path(r'^add_address/(?P<sign>[0-9]+)/$', address_view.add_address),
    re_path(r'^update_address/(?P<address_id>[0-9]+)/(?P<sign>[0-9]+)/$', address_view.update_address),
    re_path(r'^delete_address/(?P<address_id>[0-9]+)/(?P<sign>[0-9]+)/$', address_view.delete_address),
    path('create_order/', orders_view.create_order),
    re_path(r'view_orders/(?P<orders_id>[0-9]+)/$', orders_view.view_orders),
    path('view_all_orders/', orders_view.view_all_orders),
    re_path(r'delete_orders/(?P<orders_id>[0-9]+)/(?P<sign>[0-9]+)/$', orders_view.delete_orders),
]+ static(settings.STATIC_URL, document_root = settings.STATICFILES_DIRS)+\
    static(settings.STATIC_URL, document_root = settings.STATICFILES_DIRS)

goods/models.py
from django.db import models

# Create your models here.
# 用户信息
class User(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.username
# 收货地址
class Address(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)     # 外键
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)

    def __str__(self):
        return self.address

# 商品
class Goods(models.Model):
    goods_name = models.CharField(max_length=100)   # 字符串类型，必须设置max_length属性，而且时正整数
    goods_price = models.FloatField()               # 浮点类型
    picture = models.FileField(upload_to='./upload/')      # 文件类型，必须设置upload_to
    description = models.TextField()                # 文本类型

    def __str__(self):
        return self.goods_name

# 总订单
class Orders(models.Model):
    address = models.ForeignKey(Address,on_delete=models.CASCADE)
    creat_time = models.DateTimeField(auto_now=True)   # 时间字段
    status = models.BooleanField()     #订单状态

    def __str__(self):
        return self.creat_time

# 单个订单
class Order(models.Model):
    order = models.ForeignKey(Orders,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)
    count = models.IntegerField()

goods/forms.py
from django import forms

from goods.models import Address


class UserForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=100)
    # widget=forms.PasswordInput() 表示文本信息为密码格式
    password = forms.CharField(label='密码', widget=forms.PasswordInput())
    email = forms.EmailField(label='电子邮箱')

class LoginForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=100)
    password = forms.CharField(label='密码', widget=forms.PasswordInput())

class ChangePasswordForm(forms.Form):
    oldpassword = forms.CharField(label='旧密码', widget=forms.PasswordInput())
    newpassword = forms.CharField(label='新密码', widget=forms.PasswordInput())
    checkpassword = forms.CharField(label='确认密码', widget=forms.PasswordInput())

class AddressForm(forms.Form):
    address = forms.CharField(label='地址', max_length=100)
    phone = forms.CharField(label='电话', max_length=15)

goods/views.py
from django.shortcuts import render


def page_not_found(request):
    return render(request, '404.html')


def page_error(request):
    return render(request, '500.html')


def permission_denied(request):
    return render(request, '403.html')

goods/templates/add_address.html
{%load staticfiles%}
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>添加地址</title>
    <link href="{%static 'css/signin.css'%}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
</head>
<body>
  <div class="container">
    <form class="form-signin" method="post" enctype="multipart/form-data">
      <h2 class="form-signin-heading">添加地址</h2>
	  {% csrf_token %}
      {{uf.as_p}}
        <p style="color:red">{{error}}</p> <br>
      <button class="btn btn-lg btn-primary btn-block" type="submit">提交</button><br>
    </form>
  </div> <!-- /container -->
</body>
</html>

goods/templates/base.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=Edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
{#      <meta name="viewport" content="width=device-width, initial-scale=1">#}
      <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
      <meta name="description" content="">
      <meta name="author" content="">

      <title>电子商务系统</title>
   <link href="{%static 'css/signin.css'%}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
  </head>

  <body role="document">
<!-- 导航栏 -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/goods_view/">电子商务系统</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/goods_view/">商品列表</a></li>
			<li class="active"><a href="/view_all_orders/">查看所有订单</a></li>
  {% block content %}


  {% endblock %}
  <div class="container theme-showcase" role="main">
      <div class="page-header"></div>
      <footer class="footer">
          <p>&copy; Company 2019,作者：黄蓉蓉</p>
      </footer>
  </div> <!-- /container -->
  <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
  <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>

</html>

goods/templates/change_password.html
{% extends "base.html" %}
{% block content %}
            <li class="active"><a href="/view_chart/">查看购物车<font color="#FF0000">{{ count }}</font></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">

      <div class="page-header">
        <div id="navbar" class="navbar-collapse collapse">
        </div><!--/.navbar-collapse -->
      </div>

      <div class="row">
        <div class="col-md-6">
          <form action="/change_password/" method="post" enctype="multipart/form-data">
		  {% csrf_token %}
            <p style="color:red">{{error}}</p> <br>
              {{ uf.as_p }}
{#            旧密码：<input name="oldpassword" type="password" required><br>#}
{#            新密码：<input name="newpassword" type="password" required><br>#}
{#            确认密码：<input name="checkpassword" type="password" required><br>#}
            <input type="submit" value="修改">
          </form>
        </div>
      </div>
{% endblock %}

goods/templates/error.html
{% extends "base.html" %}
{% block content %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
	<div class="row" style="margin-top:30px">
        <div class="col-lg-6">
          <div class="input-group">
          </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
      </div><!-- /.row -->

    <div class="container theme-showcase" role="main">
      <font color="#FF0000">{{error}}</font>
    </div> <!-- /container   glyphicon glyphicon-phone border-style:none; -->
{% endblock %}

goods/templates/good_details.html
{% extends "base.html" %}
{% block content %}
            <li class="active"><a href="/view_chart/">查看购物车<font color="#FF0000">{{ count }}</font></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">
      <!--商品详情-->
      <div class="row" style="margin-top:30px">
        <div class="col-lg-6">
          <div class="input-group">
		  单价：￥{{good.goods_price}}元 <a href="/add_chart/{{good.id}}/2/">放入购物车</a><br>
		  <img src="/{{good.picture}}"><br>
		  {{good.description}}
          </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
      </div><!-- /.row -->

    </div> <!-- /container   glyphicon glyphicon-phone border-style:none; -->

{% endblock %}

goods/templates/goods_view.html
{% extends "base.html" %}
{% block content %}
            <li class="active"><a href="/view_chart/">查看购物车<font color="#FF0000">{{ count }}</font></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">

      <!--商品表单-->
      <div class="page-header">
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form" method="post" action="/search_name/">
            <div class="form-group">
			{% csrf_token %}
              <input name="good" type="text" placeholder="名称" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">搜索</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>

      <div class="row">
        <div class="col-md-6">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>编号</th>
                <th>名称</th>
                <th>价钱</th>
				<th>查看详情</th>
                <th>放入购物车</th>
              </tr>
            </thead>
            <tbody>
              {% for goods in goodss %}
                <tr>
                  <td>{{ goods.id }}</td>
                  <td>{{ goods.goods_name }}</td>
                  <td>￥{{ goods.goods_price }}</td>
                  <td><a href="/view_goods/{{goods.id}}/">查看</a></td>
                  <td><a href="/add_chart/{{goods.id}}/1/">放入</a></td>
                </tr>
             {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
 <!-- 列表分页器 -->
    <div class="pagination">
      <span class="step-links">
        {% if goodss.has_previous %}
          <a href="?page={{ goodss.previous_page_number }}">上一页</a>
        {% endif %}
          <span class="current">
            Page {{ goodss.number }} of {{ goodss.paginator.num_pages }}.
          </span>
        {% if goodss.has_next %}
          <a href="?page={{ goodss.next_page_number }}">下一页</a>
        {% endif %}
      </span>
    </div>
{% endblock %}

goods/templates/index.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>电子商务系统-登录</title>

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/signin.css'%}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">

  </head>

  <body>

    <div class="container">
      <form class="form-signin" method="post" action="/login_action/" enctype="multipart/form-data">
	  {% csrf_token %}
        <h2 class="form-signin-heading">电子商务系统-登录</h2>
        {{uf.as_p}}
          <p style="color:red">{{error}}</p> <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button><br>
		<a href="\register\">注册</a>
      </form>

    </div> <!-- /container -->

  </body>

</html>

goods/templates/register.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>电子商务系统-注册</title>
     <link href="{%static 'css/signin.css'%}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <form  method="post" enctype="multipart/form-data">
        <h2 class="form-signin-heading">电子商务系统-注册</h2>
		{% csrf_token %}
        {{uf.as_p}}
          <p style="color:red">{{error}}</p> <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">注册</button><br>
		<a href="/index/">登录</a>
      </form>

    </div> <!-- /container -->

  </body>

</html>

goods/templates/update_address.html
{%load staticfiles%}
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>修改地址</title>
    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/signin.css'%}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
</head>
<body>

  <div class="container">
    <form class="form-signin" method="post" enctype="multipart/form-data">
      <h2 class="form-signin-heading">修改地址</h2>
	  {% csrf_token %}
       <p><label for="id_address">地址:</label>
           <input type="text"  value="{{address.address}}" name="address" style="width: 250px"
                                                     id="id_address" size="20" maxlength="100" required />
       </p>
	  <p>
          <label for="id_phone">电话:</label>
          <input type="text" value="{{address.phone}}" name="phone" id="id_phone" style="width: 250px"
                 size="20" maxlength="15" required />
      </p>
		<p style="color:red">{{error}}</p> <br>
      <button class="btn btn-lg btn-primary btn-block" type="submit">修改</button><br>
    </form>

  </div> <!-- /container -->

</body>
</html>

goods/templates/view_address.html
{% extends "base.html" %}
{% block content %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
      <div class="page-header">
        <div id="navbar" class="navbar-collapse collapse">
        </div><!--/.navbar-collapse -->
      </div>
    <div class="container theme-showcase" role="main">
	<font color="#FF0000">{{error}}</font>
      <div class="row">
        <div class="col-md-6">
		<form method="post" action="/create_order/">
		{% csrf_token %}
          <table class="table table-striped">
            <thead>
              <tr>
                <th>选择</th>
                <th>地址</th>
				<th>修改</th>
				<th>删除</th>
               </tr>
            </thead>
            <tbody>
			  {% for address in addresses %}
                <tr>
                  <td><input type="radio" value="{{address.id}}"  name="address"></td>
                  <td>{{address.address}}</td>
				  <td><a href="/update_address/{{address.id}}/2/">修改</a></td>
				  <td><a href="/delete_address/{{address.id}}/2/">删除</a></td>
                 </tr>
             {% endfor %}
            </tbody>
          </table>
		  <input type="submit" value="下一步">
		  </form><br>
		  <form method="post" action="/add_address/2/">
		  {% csrf_token %}
		  <input type="submit" value="添加地址">
		  </form>
        </div>
      </div>
{% endblock %}

goods/templates/view_all_order.html
{% extends "base.html" %}
{% block content %}

          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">

	  <div class="page-header">
        <div id="navbar" class="navbar-collapse collapse">
        </div><!--/.navbar-collapse -->
      </div>
	  {% for key1 in Orders_set %}
	  <div class="row">
        <div class="col-md-6">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>编号</th>
				<th>商品名称</th>
				<th>商品价钱</th>
				<th>个数</th>
				<th>删除</th>
              </tr>
            </thead>
            <tbody>
              {% for key2,value in key1.items %}
			  {% for key in value %}
                <tr>
                  <td><a href="/view_goods/{{key.good_id}}/">{{ key.id }}</a></td>
                  <td>{{ key.name }}</td>
                  <td>￥{{ key.price }}</td>
				  <td>{{ key.count }}</td>
				  <td><a href="/delete_orders/{{key.id}}/1/">删除</a></td>
                </tr>
			{% endfor %}
			订单编号:{{key2.id}},创建时间：{{key2.create_time}},地址：{{key2.address}} 总价钱：￥{{key2.prices}}<br>
			{% if not key2.status %}
				<input type="submit" value="支付">
			{% endif %}
			 <a href="/delete_orders/{{key2.id}}/2/">删除</a>
			 {% endfor %}
            </tbody>
          </table>
        </div>
		{% endfor %}

      </div>
{% endblock %}

goods/templates/view_chart.html
{% extends "base.html" %}
{% block content %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
	<div class="page-header">
        <div id="navbar" class="navbar-collapse collapse">
        </div><!--/.navbar-collapse -->
      </div>
    <div class="container theme-showcase" role="main">
	<font color="#FF0000">{{error}}</font>
      <div class="row">
        <div class="col-md-6">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>编号</th>
                <th>名称</th>
                <th>价钱</th>
				<th>个数</th>
                <th>移除</th>
              </tr>
            </thead>
            <tbody>
			  {% for key in goodss %}
                <tr>
                  <td><a href="/view_goods/{{key.id}}/">{{key.id}}</a></td>
                  <td>{{key.name}}</td>
                  <td>￥{{key.price}}</td>
                  <td>
                      <form action="/update_chart/{{key.id}}/" method="post">
				      {% csrf_token %}
				      <input type="number" value="{{key.count}}" style="width:60px;" name="count{{key.id}}"
                             class="vIntegerField" id="id_count" required />
				      <input type="submit" value="修改" />
                      </form>
                  </td>
                  <td><a href="/remove_chart/{{key.id}}/">移除</a></td>
                </tr>
             {% endfor %}
            </tbody>
          </table>
		  <form method="get" action="/remove_chart_all/">
		  {% csrf_token %}
		  <input type="submit" value="清除所有">
		  </form>
		  <form method="get" action="/view_address/">
		  {% csrf_token %}
		  <input type="submit" value="生成订单">
		  </form>
        </div>

      </div>
{% endblock %}

goods/templates/view_order.html
{% extends "base.html" %}
{% block content %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">

	  <div class="page-header">
        <div id="navbar" class="navbar-collapse collapse">
        </div><!--/.navbar-collapse -->
      </div>
	  <p>生成时间：{{orders.creat_time}} 配货地址：{{address}} 总价钱：￥{{prices}}</p>

	  <div class="row">
        <div class="col-md-6">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>编号</th>
				<th>商品名称</th>
				<th>商品价钱</th>
				<th>个数</th>
				<th>删除</th>
              </tr>
            </thead>
            <tbody>
              {% for key in order %}
                <tr>
                  <td><a href="/view_goods/{{key.good_id}}/">{{ key.id }}</a></td>
                  <td>{{ key.name }}</td>
                  <td>￥{{ key.price }}</td>
				  <td>{{ key.count }}</td>
				  <td><a href="/delete_orders/{{key.id}}/3/">删除</a></td>
                </tr>
             {% endfor %}
            </tbody>
          </table>
		<input type="submit" value="支付">
        </div>
      </div>
{% endblock %}

goods/templates/view_user.html
{% extends "base.html" %}
{% block content %}
    <li class="active"><a href="/view_chart/">查看购物车<font color="#FF0000">{{ count }}</font></a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
        </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">
      <div class="page-header">
        <div id="navbar" class="navbar-collapse collapse">
        </div><!--/.navbar-collapse -->
      </div>

      <div class="row">
        <div class="col-md-6">
          用户名：{{user_info.username}}<br>
          Email:{{user_info.email}}<br>
          <form action="/change_password/" method="get">
		  {% csrf_token %}
            <input type="submit" value="修改密码">
          </form>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>编号</th>
				<th>地址</th>
				<th>电话</th>
				<th>修改</th>
				<th>删除</th>
              </tr>
            </thead>
            <tbody>
              {% for key in address %}
                <tr>
                  <td>{{key.id}}</td>
                  <td>{{key.address}}</td>
				  <td>{{key.phone}}</td>
				  <td><a href="/update_address/{{key.id}}/1/">修改</a></td>
				  <td><a href="/delete_address/{{key.id}}/1/">删除</a></td>
                </tr>
             {% endfor %}
            </tbody>
          </table>
		  </form><br>
		  <form method="post" action="/add_address/1/">
		  {% csrf_token %}
		  <input type="submit" value="添加地址">
		  </form>
        </div>
     </div>
    </div>
{% endblock %}